import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <header
        style={{
          backgroundColor: "pink",
          padding: "1rem",
        }}
      >
        hiee Hello
      </header>

      {children}

      <footer
        style={{
          backgroundColor: "red",
          padding: "1rem",
        }}
      >
        kaisa hoo
      </footer>
    </>
  );
}
